# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches: [main]

jobs:
  release-to-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        env:
          UV_INDEX_NEOPALLIUM_PASSWORD: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          pip install uv
          uv venv
          uv build
          uv publish --index Neopallium -u __token__ -p $UV_INDEX_NEOPALLIUM_PASSWORD
